#!/usr/bin/env python3
"""
accord.py — The Accord System
Sacrifice | Phoenix DevOps OS | jwl247 | GPL v3

Any player can challenge any other player.
The challenger names the accord — that name becomes permanent world history.
Rules are set by the challenger. Both parties sign via master key.
Frank witnesses, enforces, and archives.
The outcome is immutable and public in both jackets.

GDD §7 — The Accord System
"""

from __future__ import annotations

import hashlib
import hmac
import json
import logging
import time
import uuid
from dataclasses import dataclass, field
from enum import Enum
from typing import Optional

from .draft_card import derive_player_id

log = logging.getLogger("accord")


# ---------------------------------------------------------------------------
# Enums
# ---------------------------------------------------------------------------

class AccordStatus(Enum):
    PROPOSED   = "proposed"    # Challenger created, awaiting opponent signature
    SIGNED     = "signed"      # Both parties signed — Frank witnessed
    ACTIVE     = "active"      # Accord is in progress
    CONCLUDED  = "concluded"   # Outcome recorded, immutable
    VOIDED     = "voided"      # One party failed to sign within window, or Frank rejected


class AccordOutcome(Enum):
    CHALLENGER_VICTORY = "challenger_victory"
    DEFENDER_VICTORY   = "defender_victory"
    DRAW               = "draw"
    FORFEIT_CHALLENGER = "forfeit_challenger"   # challenger abandoned
    FORFEIT_DEFENDER   = "forfeit_defender"     # defender abandoned
    DISRUPTED          = "disrupted"            # broken by the AO disruptor — no victor


class AccordType(Enum):
    OPEN_CHALLENGE    = "open_challenge"     # any terms the challenger sets
    KING_THEATER      = "king_theater"       # auto-generated by King of Theater system
    TRIBUNAL_DUEL     = "tribunal_duel"      # tribunal orders it in lieu of execution
    HONOR_BOUT        = "honor_bout"         # mutual honor, no stakes
    TERRITORY         = "territory"          # AO dominance at stake


# Frank's own signing identity. Used only for compulsory accords the law
# imposes (a King cannot refuse a challenge; a tribunal orders a duel).
# Frank never holds a player's master key — he signs as himself.
FRANK_AUTHORITY = "FRANK_AUTHORITY"


# ---------------------------------------------------------------------------
# Accord Terms — challenger sets every rule
# ---------------------------------------------------------------------------

@dataclass
class AccordTerms:
    """
    The challenger writes every rule.
    These are immutable after the accord is signed.
    """
    accord_name:        str                  # Name — permanent world history entry
    accord_type:        AccordType           = AccordType.OPEN_CHALLENGE

    # Stakes
    territory_stake:    Optional[str]        = None   # AO or named ground at stake
    rank_stake:         Optional[str]        = None   # rank forfeiture if lost
    equipment_stake:    Optional[str]        = None   # specific equipment wagered
    honor_stake:        bool                 = False  # honor-only, no material stakes

    # Engagement rules
    time_limit_hours:   float                = 24.0   # accord window in real hours
    theater:            str                  = "open_world"
    allowed_mos:        list[str]            = field(default_factory=list)   # empty = all
    vehicle_allowed:    bool                 = True
    squad_size_limit:   Optional[int]        = None   # None = no limit
    observer_allowed:   bool                 = True   # others can watch

    # Pay-to-win transparency (GDD §7.4 — no hidden advantages)
    pay_advantages_disclosed: dict           = field(default_factory=dict)

    def to_dict(self) -> dict:
        return {
            "accord_name":             self.accord_name,
            "accord_type":             self.accord_type.value,
            "territory_stake":         self.territory_stake,
            "rank_stake":              self.rank_stake,
            "equipment_stake":         self.equipment_stake,
            "honor_stake":             self.honor_stake,
            "time_limit_hours":        self.time_limit_hours,
            "theater":                 self.theater,
            "allowed_mos":             self.allowed_mos,
            "vehicle_allowed":         self.vehicle_allowed,
            "squad_size_limit":        self.squad_size_limit,
            "observer_allowed":        self.observer_allowed,
            "pay_advantages_disclosed": self.pay_advantages_disclosed,
        }


# ---------------------------------------------------------------------------
# Accord — the binding document
# ---------------------------------------------------------------------------

@dataclass
class Accord:
    """
    A signed accord between two players.
    Frank witnesses at signing. Outcome is immutable.
    Both jackets carry this forever.
    """
    accord_id:       str
    accord_name:     str           # Permanent world history entry

    challenger_id:   str
    challenger_card: str
    defender_id:     str
    defender_card:   str

    terms:           AccordTerms
    status:          AccordStatus  = AccordStatus.PROPOSED

    # Signatures — derived from master key HMAC over terms_hash
    terms_hash:            Optional[str]   = None
    challenger_signature:  Optional[str]   = None
    defender_signature:    Optional[str]   = None
    frank_witness_hash:    Optional[str]   = None  # Frank's seal
    defender_compelled:    bool            = False # Frank signed for the defender by law

    proposed_ts:     float                 = field(default_factory=time.time)
    signed_ts:       Optional[float]       = None
    concluded_ts:    Optional[float]       = None
    expires_ts:      Optional[float]       = None  # set at signing

    outcome:         Optional[AccordOutcome] = None
    outcome_detail:  Optional[str]           = None

    # Observers who watched — recorded in world history
    observers:       list[str]             = field(default_factory=list)

    def to_dict(self) -> dict:
        return {
            "accord_id":              self.accord_id,
            "accord_name":            self.accord_name,
            "challenger_id":          self.challenger_id,
            "challenger_card":        self.challenger_card,
            "defender_id":            self.defender_id,
            "defender_card":          self.defender_card,
            "terms":                  self.terms.to_dict(),
            "status":                 self.status.value,
            "terms_hash":             self.terms_hash,
            "challenger_signature":   self.challenger_signature,
            "defender_signature":     self.defender_signature,
            "frank_witness_hash":     self.frank_witness_hash,
            "defender_compelled":     self.defender_compelled,
            "proposed_ts":            self.proposed_ts,
            "signed_ts":              self.signed_ts,
            "concluded_ts":           self.concluded_ts,
            "expires_ts":             self.expires_ts,
            "outcome":                self.outcome.value if self.outcome else None,
            "outcome_detail":         self.outcome_detail,
            "observers":              self.observers,
        }


# ---------------------------------------------------------------------------
# Signature helpers
# ---------------------------------------------------------------------------

def _hash_terms(terms: AccordTerms) -> str:
    """Deterministic SHA3-256 hash of the accord terms."""
    blob = json.dumps(terms.to_dict(), sort_keys=True).encode()
    return hashlib.sha3_256(blob).hexdigest()


def _sign(master_key: bytes, terms_hash: str, player_id: str) -> str:
    """
    HMAC-SHA256 of terms_hash + player_id with master key.
    The player holds the master key. The platform never sees it.
    """
    msg = f"{terms_hash}:{player_id}".encode()
    return hmac.new(master_key, msg, hashlib.sha256).hexdigest()


def _verify_signature(master_key: bytes, terms_hash: str, player_id: str, signature: str) -> bool:
    expected = _sign(master_key, terms_hash, player_id)
    return hmac.compare_digest(expected, signature)


def verify_party(accord: Accord, master_key: bytes, party: str) -> bool:
    """
    Check a party's signature on the accord. party = "challenger" | "defender".
    For a compelled defender (or a Frank-issued challenge) pass Frank's key.
    """
    if party == "challenger":
        pid, sig = accord.challenger_id, accord.challenger_signature
    elif party == "defender":
        pid = FRANK_AUTHORITY if accord.defender_compelled else accord.defender_id
        sig = accord.defender_signature
    else:
        raise ValueError(f"Unknown party: {party}")
    if not sig or not accord.terms_hash:
        return False
    return _verify_signature(master_key, accord.terms_hash, pid, sig)


def _require_identity(master_key: bytes, player_id: str, role: str) -> None:
    """A master key proves identity: player_id = SHA3-256(master_key)."""
    if derive_player_id(master_key) != player_id:
        raise ValueError(f"{role} master key does not match player {player_id[:8]}")


def _require_terms_intact(accord: Accord) -> None:
    """Terms are immutable once hashed — any edit after signing is tampering."""
    if _hash_terms(accord.terms) != accord.terms_hash:
        raise ValueError(f"Accord {accord.accord_id[:8]} terms were altered after signing")


def _frank_seal(accord: Accord) -> str:
    """
    Frank's witness hash — seals both signatures + terms into one immutable record.
    """
    blob = json.dumps({
        "accord_id":             accord.accord_id,
        "terms_hash":            accord.terms_hash,
        "challenger_signature":  accord.challenger_signature,
        "defender_signature":    accord.defender_signature,
        "defender_compelled":    accord.defender_compelled,
        "signed_ts":             accord.signed_ts,
    }, sort_keys=True).encode()
    return hashlib.sha3_512(blob).hexdigest()


# ---------------------------------------------------------------------------
# Core operations
# ---------------------------------------------------------------------------

def propose_accord(
    challenger_id:   str,
    challenger_card: str,
    challenger_key:  bytes,
    defender_id:     str,
    defender_card:   str,
    terms:           AccordTerms,
) -> Accord:
    """
    Challenger creates and signs the accord.
    Accord is PROPOSED until the defender countersigns.
    The challenger's key must be theirs (or Frank's, for FRANK_AUTHORITY).
    """
    if challenger_id == defender_id:
        raise ValueError("A player cannot challenge themselves")
    if not terms.accord_name or not terms.accord_name.strip():
        raise ValueError("The challenger must name the accord")
    if terms.time_limit_hours <= 0:
        raise ValueError("Accord time limit must be positive")
    if challenger_id != FRANK_AUTHORITY:
        _require_identity(challenger_key, challenger_id, "Challenger")

    accord_id  = str(uuid.uuid4())
    terms_hash = _hash_terms(terms)
    sig        = _sign(challenger_key, terms_hash, challenger_id)

    accord = Accord(
        accord_id             = accord_id,
        accord_name           = terms.accord_name,
        challenger_id         = challenger_id,
        challenger_card       = challenger_card,
        defender_id           = defender_id,
        defender_card         = defender_card,
        terms                 = terms,
        status                = AccordStatus.PROPOSED,
        terms_hash            = terms_hash,
        challenger_signature  = sig,
    )

    log.info(
        f"Accord proposed: '{terms.accord_name}' "
        f"({challenger_id[:8]} → {defender_id[:8]}) id={accord_id[:8]}"
    )
    return accord


def countersign_accord(
    accord:       Accord,
    defender_key: bytes,
) -> Accord:
    """
    Defender signs. Frank witnesses. Accord becomes SIGNED.
    The signing timestamp starts the clock on the time limit.
    """
    if accord.status != AccordStatus.PROPOSED:
        raise ValueError(f"Accord {accord.accord_id[:8]} is not in PROPOSED state")
    _require_terms_intact(accord)
    _require_identity(defender_key, accord.defender_id, "Defender")

    accord.defender_signature = _sign(defender_key, accord.terms_hash, accord.defender_id)
    return _seal_signed(accord)


def countersign_by_authority(accord: Accord, frank_key: bytes, reason: str) -> Accord:
    """
    Frank signs for the defender where the law compels the accord
    (King of Theater challenge, tribunal duel). The signature is Frank's,
    over FRANK_AUTHORITY — never a forged copy of the defender's.
    """
    if accord.status != AccordStatus.PROPOSED:
        raise ValueError(f"Accord {accord.accord_id[:8]} is not in PROPOSED state")
    if accord.terms.accord_type not in (AccordType.KING_THEATER, AccordType.TRIBUNAL_DUEL):
        raise ValueError("Frank only compels King of Theater and tribunal duel accords")
    _require_terms_intact(accord)

    accord.defender_signature = _sign(frank_key, accord.terms_hash, FRANK_AUTHORITY)
    accord.defender_compelled = True
    accord.outcome_detail     = f"Compelled by law: {reason}"
    return _seal_signed(accord)


def _seal_signed(accord: Accord) -> Accord:
    accord.signed_ts          = time.time()
    accord.expires_ts         = accord.signed_ts + (accord.terms.time_limit_hours * 3600)
    accord.frank_witness_hash = _frank_seal(accord)
    accord.status             = AccordStatus.SIGNED

    log.info(
        f"Accord signed: '{accord.accord_name}' "
        f"Frank seal={accord.frank_witness_hash[:16]} "
        f"expires={accord.expires_ts:.0f}"
    )
    return accord


def activate_accord(accord: Accord) -> Accord:
    """Move accord from SIGNED to ACTIVE — engagement has started."""
    if accord.status != AccordStatus.SIGNED:
        raise ValueError(f"Accord {accord.accord_id[:8]} must be SIGNED to activate")
    _require_terms_intact(accord)
    if check_expiry(accord):
        raise ValueError(f"Accord {accord.accord_id[:8]} expired before engagement")
    accord.status = AccordStatus.ACTIVE
    log.info(f"Accord active: '{accord.accord_name}'")
    return accord


def conclude_accord(
    accord:       Accord,
    outcome:      AccordOutcome,
    detail:       str = "",
    frank=None,
) -> Accord:
    """
    Record the outcome. Immutable from this point.
    Frank archives. Both jackets will carry this.
    """
    if accord.status not in (AccordStatus.SIGNED, AccordStatus.ACTIVE):
        raise ValueError(f"Accord {accord.accord_id[:8]} cannot be concluded from {accord.status.value}")

    _require_terms_intact(accord)

    if accord.expires_ts and time.time() > accord.expires_ts:
        # Past the challenger's own time limit, only a named forfeit or a
        # disruption stands; a claimed win after the clock ran out does not.
        if outcome not in (AccordOutcome.FORFEIT_CHALLENGER, AccordOutcome.FORFEIT_DEFENDER,
                           AccordOutcome.DISRUPTED):
            outcome = AccordOutcome.DRAW
            detail  = "Time limit expired — no decisive result"

    accord.outcome        = outcome
    accord.outcome_detail = detail
    accord.concluded_ts   = time.time()
    accord.status         = AccordStatus.CONCLUDED

    log.info(
        f"Accord concluded: '{accord.accord_name}' "
        f"outcome={outcome.value} — {detail}"
    )

    # Broadcast to Frank bus if attached
    if frank is not None:
        try:
            msg = json.dumps(accord.to_dict()).encode()
            frank.bus.write_stage(4, msg)
        except Exception as e:
            log.warning(f"Frank broadcast failed for accord {accord.accord_id[:8]}: {e}")

    return accord


def void_accord(accord: Accord, reason: str) -> Accord:
    """
    Void a PROPOSED accord — only valid before countersigning.
    Cannot void a SIGNED or concluded accord.
    """
    if accord.status not in (AccordStatus.PROPOSED,):
        raise ValueError(f"Cannot void accord in state {accord.status.value}")
    accord.status         = AccordStatus.VOIDED
    accord.outcome_detail = reason
    accord.concluded_ts   = time.time()
    log.info(f"Accord voided: '{accord.accord_name}' — {reason}")
    return accord


def add_observer(accord: Accord, player_id: str) -> None:
    """Register an observer. Observers are recorded in world history."""
    if accord.status not in (AccordStatus.SIGNED, AccordStatus.ACTIVE):
        raise ValueError("Can only observe a SIGNED or ACTIVE accord")
    if not accord.terms.observer_allowed:
        raise ValueError(f"Accord '{accord.accord_name}' does not permit observers")
    if player_id not in accord.observers:
        accord.observers.append(player_id)


def check_expiry(accord: Accord) -> bool:
    """Return True if accord has expired without conclusion."""
    if accord.status in (AccordStatus.CONCLUDED, AccordStatus.VOIDED):
        return False
    if accord.expires_ts and time.time() > accord.expires_ts:
        return True
    return False


# ---------------------------------------------------------------------------
# World history entry — what goes into the permanent record
# ---------------------------------------------------------------------------

def world_history_entry(accord: Accord) -> dict:
    """
    The entry written into permanent world history.
    The accord name is the headline. It lives here forever.
    """
    return {
        "type":          "accord",
        "accord_id":     accord.accord_id,
        "name":          accord.accord_name,         # permanent world history headline
        "challenger":    accord.challenger_id,
        "defender":      accord.defender_id,
        "accord_type":   accord.terms.accord_type.value,
        "outcome":       accord.outcome.value if accord.outcome else None,
        "concluded_ts":  accord.concluded_ts,
        "frank_seal":    accord.frank_witness_hash,
        "compelled":     accord.defender_compelled,
        "pay_advantages": accord.terms.pay_advantages_disclosed,
        "observer_count": len(accord.observers),
    }
