#!/usr/bin/env bash
# =============================================================================
# bootstrap.sh — Phoenix DevOps OS
# One command. Cold machine to operational Phoenix.
#
# Usage:
#   curl -fsSL https://raw.githubusercontent.com/jwl247/Phoenix-DevOps-oS/main/bootstrap.sh | bash
#   — or —
#   git clone https://github.com/jwl247/Phoenix-DevOps-oS.git ~/phoenix-devops
#   cd ~/phoenix-devops && ./bootstrap.sh
#
# Flags:
#   --dev          Use ~/projects/phoenix-devops (Jerry's dev layout)
#   --no-d1        Skip Cloudflare D1 sync (offline mode)
#   --worker-url   Override Cloudflare worker URL
#
# License: GPL v3 — Phoenix DevOps LLC / jwl247
# =============================================================================

set -euo pipefail

# ── Output helpers ────────────────────────────────────────────────────────────
G="\033[0;32m"; Y="\033[0;33m"; R="\033[0;31m"; C="\033[0;36m"
B="\033[1m";    N="\033[0m"

ok()      { echo -e "${G}  [OK]${N}      $1"; }
log()     { echo -e "${Y}  [PHOENIX]${N} $1"; }
err()     { echo -e "${R}  [ERROR]${N}   $1"; exit 1; }
warn()    { echo -e "${Y}  [WARN]${N}    $1"; }
section() { echo -e "\n${B}${C}  ── $1 ──────────────────────────────────────────────${N}"; }
banner()  {
  echo ""
  echo -e "${Y}${B}  ╔══════════════════════════════════════════╗${N}"
  echo -e "${Y}${B}  ║        PHOENIX DEVOPS OS                 ║${N}"
  echo -e "${Y}${B}  ║        bootstrap.sh                      ║${N}"
  echo -e "${Y}${B}  ║        jwl247 / GPL v3                   ║${N}"
  echo -e "${Y}${B}  ╚══════════════════════════════════════════╝${N}"
  echo ""
}

# ── Flags ─────────────────────────────────────────────────────────────────────
DEV_MODE=0
SKIP_D1=0
WORKER_URL="https://packages-worker.phoenix-jwl.workers.dev"

for arg in "${@:-}"; do
  case "$arg" in
    --dev)         DEV_MODE=1 ;;
    --no-d1)       SKIP_D1=1  ;;
    --worker-url=*) WORKER_URL="${arg#*=}" ;;
  esac
done

banner

# ── Platform detection ────────────────────────────────────────────────────────
section "Detecting platform"

detect_platform() {
  if grep -qi microsoft /proc/version 2>/dev/null; then echo "wsl2"; return; fi
  case "$(uname -s)" in
    Linux*)  echo "linux"  ;;
    Darwin*) echo "macos"  ;;
    *)       echo "linux"  ;;
  esac
}

PLATFORM=$(detect_platform)
ok "Platform: $PLATFORM"

# ── Dependency check ──────────────────────────────────────────────────────────
section "Checking dependencies"

need() { command -v "$1" &>/dev/null || err "Missing: $1 — install it and re-run"; }
need python3
need git
need curl
need pip3 || need pip

PY_VER=$(python3 -c "import sys; print(f'{sys.version_info.major}.{sys.version_info.minor}')")
if python3 -c "import sys; sys.exit(0 if sys.version_info >= (3,10) else 1)"; then
  ok "Python $PY_VER"
else
  err "Python 3.10+ required (found $PY_VER)"
fi

# ── Install location ──────────────────────────────────────────────────────────
section "Install location"

if [[ $DEV_MODE -eq 1 ]]; then
  INSTALL_DIR="$HOME/projects/phoenix-devops"
  log "Dev mode — using $INSTALL_DIR"
else
  INSTALL_DIR="$HOME/phoenix-devops"
fi

REPO_URL="https://github.com/jwl247/Phoenix-DevOps-oS.git"

if [[ -d "$INSTALL_DIR/.git" ]]; then
  ok "Repo already at $INSTALL_DIR — pulling latest"
  git -C "$INSTALL_DIR" pull --ff-only 2>/dev/null || warn "Pull skipped (local changes present)"
else
  log "Cloning Phoenix into $INSTALL_DIR …"
  git clone --recurse-submodules "$REPO_URL" "$INSTALL_DIR"
  ok "Cloned"
fi

# ── Directory structure ───────────────────────────────────────────────────────
section "Building Phoenix directory tree"

PHOENIX_HOME="$HOME/Phoenix"

for d in \
  "$PHOENIX_HOME" \
  "$PHOENIX_HOME/clonepool" \
  "$PHOENIX_HOME/bin" \
  "$PHOENIX_HOME/cards" \
  "$PHOENIX_HOME/logs" \
  "$PHOENIX_HOME/workers" \
  "$HOME/.catalog"; do
  mkdir -p "$d"
done

ok "~/Phoenix tree ready"

# ── Python dependencies ───────────────────────────────────────────────────────
section "Installing Python dependencies"

pip3 install -q -r "$INSTALL_DIR/requirements.txt" \
  && ok "numpy installed" \
  || warn "pip install had issues — check manually"

# ── Auth token ────────────────────────────────────────────────────────────────
section "Auth token"

ENV_FILE="$HOME/.phoenix_env"

if [[ -f "$ENV_FILE" ]] && grep -q "PHOENIX_AUTH" "$ENV_FILE"; then
  PHOENIX_AUTH=$(grep "PHOENIX_AUTH" "$ENV_FILE" | head -1 | cut -d'"' -f2)
  ok "Existing PHOENIX_AUTH found — keeping it"
else
  PHOENIX_AUTH=$(openssl rand -hex 32)
  ok "Generated new PHOENIX_AUTH"
fi

# ── Write ~/.phoenix_env ──────────────────────────────────────────────────────
section "Writing ~/.phoenix_env"

cat > "$ENV_FILE" <<EOF
# Phoenix DevOps OS — environment
# Generated by bootstrap.sh on $(date -Iseconds)
# Source every session: source ~/.phoenix_env

export PHOENIX_HOME="$PHOENIX_HOME"
export PHOENIX_INSTALL_DIR="$INSTALL_DIR"
export PHOENIX_CLONEPOOL="$PHOENIX_HOME/clonepool"
export PHOENIX_BIN="$PHOENIX_HOME/bin"
export PHOENIX_CARDS="$PHOENIX_HOME/cards"
export PHOENIX_LOG="$PHOENIX_HOME/logs/phoenix.log"

export PHOENIX_SECTOR1="$INSTALL_DIR/sector1"
export PHOENIX_SECTOR2="$INSTALL_DIR/sector2"
export PHOENIX_SECTOR3="$INSTALL_DIR/sector3"
export PHOENIX_SECTOR4="$INSTALL_DIR/sector4"

export PHOENIX_AUTH="$PHOENIX_AUTH"
export PHOENIX_WORKER_URL="$WORKER_URL"
export PHOENIX_PLATFORM="$PLATFORM"

export CLONEPOOL_DIR="$PHOENIX_HOME/clonepool"
export PYTHONPATH="$INSTALL_DIR:\${PYTHONPATH:-}"
export PATH="$PHOENIX_HOME/bin:\${PATH}"

alias intake="python3 $INSTALL_DIR/unitedsys/core/intake.py"
EOF

chmod 600 "$ENV_FILE"
ok "~/.phoenix_env written (mode 600)"

# ── Install lol ───────────────────────────────────────────────────────────────
section "Installing lol command"

LOL_SRC="$INSTALL_DIR/bin/lol"
LOL_DEST="$PHOENIX_HOME/bin/lol"

if [[ -f "$LOL_SRC" ]]; then
  cp "$LOL_SRC" "$LOL_DEST"
  chmod +x "$LOL_DEST"
  ok "lol installed → $LOL_DEST"
else
  warn "bin/lol not found in repo — skipping"
fi

# ── Install intake wrapper ────────────────────────────────────────────────────
section "Installing intake command"

cat > "$PHOENIX_HOME/bin/intake" <<INTAKE_EOF
#!/usr/bin/env bash
# intake — Phoenix DevOps OS clonepool command
source "\${HOME}/.phoenix_env" 2>/dev/null || true
exec python3 "$INSTALL_DIR/unitedsys/core/intake.py" "\$@"
INTAKE_EOF

chmod +x "$PHOENIX_HOME/bin/intake"
ok "intake installed → $PHOENIX_HOME/bin/intake"

# ── Initialize catalog DB ─────────────────────────────────────────────────────
section "Initializing catalog"

# Source env so Python can find unitedsys
export PYTHONPATH="$INSTALL_DIR:${PYTHONPATH:-}"

python3 - <<PYEOF
import sys, os
sys.path.insert(0, "$INSTALL_DIR")
os.environ['PYTHONPATH'] = "$INSTALL_DIR:" + os.environ.get('PYTHONPATH', '')

db_dir = os.path.expanduser('~/.catalog')
os.makedirs(db_dir, exist_ok=True)

import sqlite3
from pathlib import Path

schema_path = Path("$INSTALL_DIR/unitedsys/db/schema.sql")
db_path = Path(db_dir) / 'catalog.db'

if schema_path.exists():
    conn = sqlite3.connect(str(db_path))
    conn.executescript(schema_path.read_text())
    conn.commit()
    conn.close()
    print("  [OK]      Catalog DB initialized at ~/.catalog/catalog.db")
else:
    print("  [WARN]    schema.sql not found — catalog DB skipped")
PYEOF

# ── Add to shell profile ──────────────────────────────────────────────────────
section "Shell profile"

PROFILE=""
if [[ -f "$HOME/.zshrc" ]];  then PROFILE="$HOME/.zshrc";
elif [[ -f "$HOME/.bashrc" ]]; then PROFILE="$HOME/.bashrc"; fi

SOURCE_LINE="[ -f \"\$HOME/.phoenix_env\" ] && source \"\$HOME/.phoenix_env\""

if [[ -n "$PROFILE" ]]; then
  if ! grep -q "phoenix_env" "$PROFILE"; then
    echo "" >> "$PROFILE"
    echo "# Phoenix DevOps OS" >> "$PROFILE"
    echo "$SOURCE_LINE" >> "$PROFILE"
    ok "Added source line to $PROFILE"
  else
    ok "$PROFILE already sources phoenix_env"
  fi
else
  warn "Could not detect shell profile — add this manually:"
  warn "$SOURCE_LINE"
fi

# ── D1 connection check ───────────────────────────────────────────────────────
if [[ $SKIP_D1 -eq 0 ]]; then
  section "Cloudflare D1 connection"
  HTTP=$(curl -s -o /dev/null -w "%{http_code}" \
    -H "Authorization: Bearer $PHOENIX_AUTH" \
    "$WORKER_URL/health" 2>/dev/null || echo "000")
  if [[ "$HTTP" == "200" ]]; then
    ok "D1 worker reachable ($WORKER_URL)"
  else
    warn "D1 worker returned HTTP $HTTP — offline mode active (intake will skip D1 sync)"
  fi
fi

# ── Run config centralizer ────────────────────────────────────────────────────
section "Scanning sectors"

if [[ -f "$INSTALL_DIR/sector2/config_centralizer.py" ]]; then
  python3 "$INSTALL_DIR/sector2/config_centralizer.py" "$INSTALL_DIR" 2>/dev/null \
    && ok "Sector scan complete — cards written to $PHOENIX_HOME/cards" \
    || warn "Config centralizer had issues — run manually after sourcing env"
fi

# ── Done ──────────────────────────────────────────────────────────────────────
echo ""
echo -e "${G}${B}  ╔══════════════════════════════════════════╗${N}"
echo -e "${G}${B}  ║        PHOENIX IS READY                  ║${N}"
echo -e "${G}${B}  ╚══════════════════════════════════════════╝${N}"
echo ""
echo -e "  ${B}Next steps:${N}"
echo -e "  ${C}1.${N} source ~/.phoenix_env"
echo -e "  ${C}2.${N} intake status"
echo -e "  ${C}3.${N} lol <file.lol>   # pull anything from the pool"
echo ""
echo -e "  ${B}Install dir:${N}  $INSTALL_DIR"
echo -e "  ${B}Phoenix home:${N} $PHOENIX_HOME"
echo -e "  ${B}Platform:${N}     $PLATFORM"
echo ""
if [[ $PLATFORM == "wsl2" ]]; then
  echo -e "  ${Y}WSL2 detected.${N} For the full kernel install (frank3 slot modules):"
  echo -e "  Run ${C}sudo bash $INSTALL_DIR/sector1/install.sh${N} after sourcing env."
  echo ""
fi
