#!/usr/bin/env bash
# phoenix-shares.sh — a box's disks on the mesh as Windows drive letters (SMB), nowhere else
# Phoenix DevOps OS | jwl247 | GPL v3
#
#   sudo SMB_PASS_FILE=/root/.smbpass bash phoenix-shares.sh apply   # password read from a 0600 file, never argv
#   sudo bash phoenix-shares.sh check | heal
#
# Rules: Samba listens ONLY on the mesh (nebula1) — never the LAN or the internet; only mesh addresses
# allowed; SMB3 with encryption REQUIRED (on top of Nebula's); one user; the old disk is mounted and
# shared READ-ONLY. Versioned (/etc/phoenix/shares.VERSION), self-healing (timer, 15 min), audited.
set -euo pipefail
VERSION="shares-1.0.2"
STATE=/etc/phoenix
USER_NAME="${SHARE_USER:-a}"
DATA=/srv/pbmiii
OLD_UUID="9d35bab9-b0ab-455a-924f-7c166e7940ef"   # 1 TB Seagate: the previous Debian install (2026-10-06 rebuild; was 97eb0325..., gone)
OLD_MNT=/mnt/pbmiii-old
log() { logger -t phoenix-shares "$*"; echo "$*"; }
[[ $EUID -eq 0 ]] || { echo "run with sudo"; exit 1; }
mkdir -p $STATE

smb_conf() {
  local mesh_ip; mesh_ip=$(ip -4 -br addr show nebula1 | awk '{print $3}')
  [[ -n "$mesh_ip" ]] || { echo "nebula1 has no address - mesh down"; exit 1; }
  cat <<EOF
# Phoenix shares ($VERSION) — generated by phoenix-shares.sh; edit the script, not this file
[global]
   workgroup = PHOENIX
   server string = pbmIII (Phoenix Mesh)
   interfaces = $mesh_ip 127.0.0.1/8
   bind interfaces only = yes
   hosts allow = 10.42.0.0/16 127.0.0.1
   hosts deny = 0.0.0.0/0
   server min protocol = SMB3
   smb encrypt = required
   server signing = mandatory
   map to guest = never
   restrict anonymous = 2
   load printers = no
   printing = bsd
   printcap name = /dev/null
   disable spoolss = yes
   disable netbios = yes
   smb ports = 445
   log level = 1 auth_audit:3
   logging = systemd

[pbmIII]
   comment = pbmIII main disk (read-write)
   path = $DATA
   valid users = $USER_NAME
   read only = no
   create mask = 0640
   directory mask = 0750

[pbmIII-old]
   comment = pbmIII old disk (READ-ONLY)
   path = $OLD_MNT
   valid users = $USER_NAME
   read only = yes
EOF
}

apply() {
  [[ -n "${SMB_PASS_FILE:-}" && -s "$SMB_PASS_FILE" ]] || { echo "SMB_PASS_FILE (0600) required"; exit 1; }
  DEBIAN_FRONTEND=noninteractive apt-get -y -q install samba >/dev/null
  install -d -m 750 -o "$USER_NAME" -g "$USER_NAME" $DATA
  install -d -m 755 $OLD_MNT
  grep -q "$OLD_UUID" /etc/fstab || echo "UUID=$OLD_UUID $OLD_MNT ext4 ro,nofail,noexec,nosuid,nodev 0 2" >> /etc/fstab
  systemctl daemon-reload
  mountpoint -q $OLD_MNT || mount $OLD_MNT
  smb_conf > /etc/samba/smb.conf
  testparm -s /etc/samba/smb.conf >/dev/null 2>&1
  cp /etc/samba/smb.conf $STATE/smb.known-good
  pw=$(cat "$SMB_PASS_FILE")
  printf '%s\n%s\n' "$pw" "$pw" | smbpasswd -s -a "$USER_NAME" >/dev/null
  shred -u "$SMB_PASS_FILE" 2>/dev/null || rm -f "$SMB_PASS_FILE"
  systemctl disable --now nmbd >/dev/null 2>&1 || true; systemctl mask nmbd >/dev/null 2>&1 || true
  systemctl enable smbd >/dev/null 2>&1; systemctl restart smbd
  echo "-w /etc/samba/ -p wa -k shares" > /etc/audit/rules.d/91-phoenix-shares.rules
  augenrules --load >/dev/null 2>&1 || true
  echo "$VERSION applied $(date -Is)" > $STATE/shares.VERSION
  install -m 755 "$(readlink -f "$0")" /usr/local/sbin/phoenix-shares
  printf '[Unit]\nDescription=Phoenix shares self-heal\n[Service]\nType=oneshot\nExecStart=/usr/local/sbin/phoenix-shares heal\n' \
    > /etc/systemd/system/phoenix-shares-heal.service
  printf '[Unit]\nDescription=Phoenix shares self-heal every 15 min\n[Timer]\nOnBootSec=3min\nOnUnitActiveSec=15min\nPersistent=true\n[Install]\nWantedBy=timers.target\n' \
    > /etc/systemd/system/phoenix-shares-heal.timer
  systemctl daemon-reload; systemctl enable --now phoenix-shares-heal.timer >/dev/null 2>&1
  log "shares $VERSION applied: [pbmIII] rw $DATA, [pbmIII-old] ro $OLD_MNT — mesh only"
}

drift() {
  cmp -s /etc/samba/smb.conf $STATE/smb.known-good || echo "smb.conf"
  systemctl is-active -q smbd || echo "smbd"
  mountpoint -q $OLD_MNT || echo "old-disk-mount"
  local opts; opts=$(findmnt -no OPTIONS $OLD_MNT 2>/dev/null || true)
  [[ -z "$opts" || ",$opts," == *",ro,"* ]] || echo "old-disk-writable"
  local listen; listen=$(ss -ltnH 'sport = :445' 2>/dev/null || true)
  grep -qE '0\.0\.0\.0:445|\[::\]:445|\*:445|192\.168\.' <<<"$listen" && echo "smb-exposed"
  grep -q '10\.42\.' <<<"$listen" || echo "smb-not-on-mesh"
  true
}

heal() {
  local d; d=$(drift); [[ -z "$d" ]] && return 0
  for item in $d; do
    case "$item" in
      smb.conf|smb-exposed|smb-not-on-mesh) cp $STATE/smb.known-good /etc/samba/smb.conf; systemctl restart smbd ;;
      smbd) systemctl restart smbd ;;
      old-disk-mount) mount $OLD_MNT || { log "heal FAILED: old-disk-mount (mount $OLD_MNT refused)"; continue; } ;;
      old-disk-writable) mount -o remount,ro $OLD_MNT ;;
    esac
    log "drift healed: $item ($(cat $STATE/shares.VERSION 2>/dev/null))"
  done
}

case "${1:-check}" in
  apply) apply ;;
  check) d=$(drift); [[ -z "$d" ]] && echo "clean ($(cat $STATE/shares.VERSION 2>/dev/null))" || { echo "DRIFT:"; echo "$d" | sed 's/^/  /'; exit 1; } ;;
  heal)  heal ;;
  *) echo "usage: phoenix-shares.sh apply|check|heal"; exit 2 ;;
esac
