#!/usr/bin/env bash
# install.sh — Life First, one-step installer
# Phoenix DevOps OS | jwl247 | GPL v3
#
# Replaces lifefirst_setup.sh + deploy_lifefirst.sh (Ubuntu-specific, hardcoded
# secrets, two overlapping scripts) with ONE idempotent installer for Debian
# (matches Phoenix's QEMU PoC box) or Ubuntu.
#
# What it does:
#   1. Installs Apache, MariaDB, PHP 8 + extensions (apt, Debian/Ubuntu both work)
#   2. Generates real random secrets on first run — never hardcoded, never
#      regenerated on a re-run (re-running this script is always safe)
#   3. Creates the lifefirst database + user, loads the schema (users: you + laurie)
#   4. Deploys all 7 AI modules + the API router + secure_settings
#   5. Writes /etc/lifefirst/lifefirst.env + an Apache vhost that exposes it to PHP
#   6. Installs a systemd service that runs the notification escalation loop
#      (module 6's escalate/check need something calling them — this is that)
#   7. Prints the local test URL + the next step (cloudflared tunnel)
#
# USAGE (as root, on the target Debian/Ubuntu box):
#   sudo bash install.sh
#
# Safe to re-run: re-running never touches an existing secret, re-deploys the
# PHP modules (so `git pull && sudo bash install.sh` is how you update), and
# reloads Apache. It does NOT re-run the SQL schema against an existing DB
# (CREATE TABLE IF NOT EXISTS in module_1 makes that safe too, but we skip the
# INSERT of the seed users so a second run can't duplicate them).

set -euo pipefail

if [[ $EUID -ne 0 ]]; then
    echo "Re-running with sudo..."
    exec sudo bash "$0" "$@"
fi

# ── paths ────────────────────────────────────────────────────────────────────
SRC_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
WEB_ROOT="/var/www/html/lifefirst"
ENV_DIR="/etc/lifefirst"
ENV_FILE="$ENV_DIR/lifefirst.env"
VHOST_FILE="/etc/apache2/sites-available/lifefirst.conf"
ESCALATOR_UNIT="/etc/systemd/system/lifefirst-escalator.service"

# ── colours ──────────────────────────────────────────────────────────────────
G='\033[0;32m'; R='\033[0;31m'; Y='\033[1;33m'; C='\033[0;36m'; B='\033[1m'; N='\033[0m'
ok()   { echo -e "${G}[OK]${N} $*"; }
warn() { echo -e "${Y}[!]${N} $*"; }
bad()  { echo -e "${R}[FAIL]${N} $*"; exit 1; }
hdr()  { echo -e "\n${C}${B}── $* ──${N}"; }

# =============================================================================
hdr "1. Packages (Apache, MariaDB, PHP)"
# =============================================================================
export DEBIAN_FRONTEND=noninteractive
if ! command -v apache2 >/dev/null 2>&1 || ! command -v mysql >/dev/null 2>&1 || ! command -v php >/dev/null 2>&1; then
    apt-get update -qq
    apt-get install -y -qq apache2 mariadb-server php php-mysqli php-curl php-mbstring \
        libapache2-mod-php default-mysql-client >/dev/null
    ok "packages installed"
else
    ok "packages already present"
fi
a2enmod rewrite >/dev/null 2>&1 || true
systemctl enable --now apache2 mariadb >/dev/null 2>&1
ok "apache2 + mariadb running"

# =============================================================================
hdr "2. Secrets — generated once, kept forever after"
# =============================================================================
mkdir -p "$ENV_DIR"
chmod 750 "$ENV_DIR"

# Load any existing env so re-runs never regenerate a live secret.
if [[ -f "$ENV_FILE" ]]; then
    # shellcheck disable=SC1090
    source <(grep -E '^LF_|^CLAUDE_|^OLLAMA_' "$ENV_FILE" | sed 's/^/export /')
    ok "existing secrets loaded from $ENV_FILE — not touching them"
fi

LF_DB_HOST="${LF_DB_HOST:-localhost}"
LF_DB_NAME="${LF_DB_NAME:-lifefirst}"
LF_DB_USER="${LF_DB_USER:-lifefirst}"
LF_DB_PASS="${LF_DB_PASS:-$(openssl rand -base64 24 | tr -d '=+/')}"
LF_API_SECRET="${LF_API_SECRET:-$(openssl rand -hex 32)}"
CLAUDE_API_KEY="${CLAUDE_API_KEY:-}"
OLLAMA_URL="${OLLAMA_URL:-http://localhost:11434}"

cat > "$ENV_FILE" <<EOF
# Life First — generated by install.sh. Re-running install.sh keeps these.
LF_DB_HOST=$LF_DB_HOST
LF_DB_NAME=$LF_DB_NAME
LF_DB_USER=$LF_DB_USER
LF_DB_PASS=$LF_DB_PASS
LF_API_SECRET=$LF_API_SECRET
CLAUDE_API_KEY=$CLAUDE_API_KEY
OLLAMA_URL=$OLLAMA_URL
EOF
chmod 600 "$ENV_FILE"
ok "secrets in $ENV_FILE (mode 600, root only)"

# =============================================================================
hdr "3. Database"
# =============================================================================
DB_ALREADY_EXISTS=$(mysql -N -e "SHOW DATABASES LIKE '$LF_DB_NAME';" 2>/dev/null | grep -c "$LF_DB_NAME" || true)

mysql -e "CREATE DATABASE IF NOT EXISTS \`$LF_DB_NAME\` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;"
mysql -e "CREATE USER IF NOT EXISTS '$LF_DB_USER'@'localhost' IDENTIFIED BY '$LF_DB_PASS';"
mysql -e "ALTER USER '$LF_DB_USER'@'localhost' IDENTIFIED BY '$LF_DB_PASS';"
mysql -e "GRANT ALL PRIVILEGES ON \`$LF_DB_NAME\`.* TO '$LF_DB_USER'@'localhost'; FLUSH PRIVILEGES;"
ok "database + user ready"

if [[ "$DB_ALREADY_EXISTS" == "0" ]]; then
    mysql "$LF_DB_NAME" < "$SRC_DIR/module_1_database.sql"
    ok "schema loaded, seed users (you + laurie) created"
    if [[ -f "$SRC_DIR/secure_settings_schema.sql" ]]; then
        mysql "$LF_DB_NAME" < "$SRC_DIR/secure_settings_schema.sql"
        ok "secure_settings schema loaded"
    fi
else
    warn "database already existed — schema/seed NOT re-run (safe re-install). Run migrations by hand if the schema changed."
fi

# =============================================================================
hdr "4. Deploy the app"
# =============================================================================
mkdir -p "$WEB_ROOT"
for f in config.php module_2_api_router.php module_3_schedule_ai.php module_4_messenger_ai.php \
         module_5_ai_memory.php module_6_notification_ai.php module_7_voice_ai.php secure_settings.php; do
    if [[ -f "$SRC_DIR/$f" ]]; then
        cp "$SRC_DIR/$f" "$WEB_ROOT/"
    fi
done
# api.php is what the outside world calls — module_2 IS the router.
cp "$SRC_DIR/module_2_api_router.php" "$WEB_ROOT/api.php"

# Laurie's zero-install front door — see laurie/index.html.
if [[ -d "$SRC_DIR/laurie" ]]; then
    mkdir -p "$WEB_ROOT/laurie"
    cp "$SRC_DIR/laurie/"*.html "$SRC_DIR/laurie/"*.php "$WEB_ROOT/laurie/" 2>/dev/null || true
fi

chown -R www-data:www-data "$WEB_ROOT"
find "$WEB_ROOT" -type f -name '*.php' -exec chmod 640 {} \;
find "$WEB_ROOT" -type d -exec chmod 750 {} \;
chmod 755 "$WEB_ROOT" "$WEB_ROOT/laurie" 2>/dev/null || true
ok "app deployed to $WEB_ROOT"

# =============================================================================
hdr "5. Apache vhost (env vars -> PHP via SetEnv)"
# =============================================================================
cat > "$VHOST_FILE" <<EOF
<VirtualHost *:80>
    DocumentRoot $WEB_ROOT
    <Directory $WEB_ROOT>
        AllowOverride All
        Require all granted
    </Directory>

    SetEnv LF_DB_HOST "$LF_DB_HOST"
    SetEnv LF_DB_NAME "$LF_DB_NAME"
    SetEnv LF_DB_USER "$LF_DB_USER"
    SetEnv LF_DB_PASS "$LF_DB_PASS"
    SetEnv LF_API_SECRET "$LF_API_SECRET"
    SetEnv CLAUDE_API_KEY "$CLAUDE_API_KEY"
    SetEnv OLLAMA_URL "$OLLAMA_URL"

    ErrorLog \${APACHE_LOG_DIR}/lifefirst-error.log
    CustomLog \${APACHE_LOG_DIR}/lifefirst-access.log combined
</VirtualHost>
EOF
a2ensite lifefirst.conf >/dev/null 2>&1 || true
a2dissite 000-default.conf >/dev/null 2>&1 || true
apache2ctl configtest >/dev/null 2>&1 && ok "vhost config valid" || bad "apache config test failed — check $VHOST_FILE"
systemctl reload apache2
ok "apache reloaded"

# =============================================================================
hdr "6. Notification escalation loop"
# =============================================================================
# module_6's escalate/check need something calling them on an interval — that
# infrastructure never existed. Cron can't do sub-minute; a tiny systemd
# service loop matches the module's own 30s ESCALATION_INTERVAL_SECONDS.
cat > "$ESCALATOR_UNIT" <<EOF
[Unit]
Description=Life First — notification escalation loop
After=apache2.service mariadb.service

[Service]
Type=simple
ExecStart=/bin/bash -c 'while true; do \\
    curl -s -X POST http://localhost/api.php?action=request \\
        -H "Authorization: Bearer $LF_API_SECRET" -H "Content-Type: application/json" \\
        -d "{\\"username\\":\\"you\\",\\"message\\":\\"escalate notifications\\",\\"action\\":\\"escalate\\"}" \\
        > /dev/null; \\
    sleep 30; \\
done'
Restart=on-failure
RestartSec=10

[Install]
WantedBy=multi-user.target
EOF
systemctl daemon-reload
systemctl enable --now lifefirst-escalator.service
ok "escalation loop running (every 30s, matches module 6's own interval)"

# =============================================================================
hdr "Done"
# =============================================================================
IP=$(hostname -I 2>/dev/null | awk '{print $1}')
echo -e "${G}${B}Life First is up.${N}"
echo "  Local:   http://localhost/api.php?action=health"
echo "  Network: http://${IP:-<this-box-ip>}/api.php?action=health"
echo "  Laurie's front door: http://${IP:-<this-box-ip>}/laurie/"
echo ""
echo "  Next: expose it with a Cloudflare Tunnel so it's reachable off this network."
echo "    cloudflared tunnel login"
echo "    cloudflared tunnel create lifefirst"
echo "    cloudflared tunnel route dns lifefirst <your-hostname>"
echo "    cloudflared tunnel run --url http://localhost:80 lifefirst"
echo ""
echo "  Secrets are in $ENV_FILE (root-only, mode 600) — re-running this script never changes them."
