#!/usr/bin/env bash
# phoenix-harden.sh — Phoenix server baseline for Debian (versioned, self-healing, audited)
# Phoenix DevOps OS | jwl247 | GPL v3
#
#   sudo bash phoenix-harden.sh apply   --ssh-from "192.168.1.0/24" [--keep-desktop] [--keep-services]
#   sudo bash phoenix-harden.sh confirm                 # keep the new firewall (else it rolls back in 120 s)
#   sudo bash phoenix-harden.sh check                   # report drift, change nothing
#   sudo bash phoenix-harden.sh heal                    # restore drifted settings (run by the timer)
#
# What it enforces (each item maps to sector3/mesh/COMPLIANCE.md / scripts/hardening/COMPLIANCE.md):
#   firewall  nftables: drop inbound except loopback, established, ICMP/ICMPv6 essentials, DHCP,
#             Nebula UDP 4242, everything arriving on the mesh (nebula1 — Nebula's own group
#             firewall decides there), SSH only from --ssh-from networks (break-glass)
#   ssh       keys only, no root, 3 tries, 30 s grace, no X11/agent forwarding
#   services  printing/Bluetooth/mDNS/modem services off on servers (--keep-services: leave every service as set)
#   kernel    network + kernel hardening sysctls
#   audit     auditd with rules on identity, sudo, ssh and mesh config changes
#   updates   unattended security upgrades
# Firewall changes roll back automatically after 120 s unless `confirm` is run — no lockouts.
set -euo pipefail
VERSION="harden-1.0.2"
STATE=/etc/phoenix
mkdir -p "$STATE"
log() { logger -t phoenix-harden "$*"; echo "$*"; }
[[ $EUID -eq 0 ]] || { echo "run with sudo"; exit 1; }

CMD="${1:-check}"; shift || true
SSH_FROM=""; KEEP_DESKTOP=false; KEEP_SERVICES=false
while [[ $# -gt 0 ]]; do
  case "$1" in
    --ssh-from) SSH_FROM="$2"; shift 2 ;;
    --keep-desktop) KEEP_DESKTOP=true; shift ;;
    --keep-services) KEEP_SERVICES=true; shift ;;
    *) echo "unknown option $1"; exit 2 ;;
  esac
done
[[ -f $STATE/harden.conf ]] && source $STATE/harden.conf
[[ -n "${SSH_FROM_ARG:-}" && -z "$SSH_FROM" ]] && SSH_FROM="$SSH_FROM_ARG"
[[ "${KEEP_SERVICES_ARG:-false}" == true ]] && KEEP_SERVICES=true

SSHD_CONF='PasswordAuthentication no
KbdInteractiveAuthentication no
PermitRootLogin no
MaxAuthTries 3
LoginGraceTime 30
X11Forwarding no
AllowAgentForwarding no
PermitEmptyPasswords no
ClientAliveInterval 300
ClientAliveCountMax 2'

SYSCTL_CONF='net.ipv4.conf.all.rp_filter = 1
net.ipv4.conf.default.rp_filter = 1
net.ipv4.conf.all.accept_redirects = 0
net.ipv4.conf.default.accept_redirects = 0
net.ipv4.conf.all.send_redirects = 0
net.ipv4.conf.all.accept_source_route = 0
net.ipv6.conf.all.accept_redirects = 0
net.ipv6.conf.default.accept_redirects = 0
net.ipv6.conf.all.accept_source_route = 0
net.ipv4.conf.all.log_martians = 1
net.ipv4.tcp_syncookies = 1
net.ipv4.icmp_echo_ignore_broadcasts = 1
kernel.kptr_restrict = 2
kernel.dmesg_restrict = 1
kernel.unprivileged_bpf_disabled = 1
kernel.yama.ptrace_scope = 1
fs.protected_hardlinks = 1
fs.protected_symlinks = 1
fs.protected_fifos = 2
fs.protected_regular = 2
fs.suid_dumpable = 0'

AUDIT_RULES='-w /etc/passwd -p wa -k identity
-w /etc/group -p wa -k identity
-w /etc/shadow -p wa -k identity
-w /etc/sudoers -p wa -k sudo
-w /etc/sudoers.d/ -p wa -k sudo
-w /etc/ssh/sshd_config -p wa -k sshd
-w /etc/ssh/sshd_config.d/ -p wa -k sshd
-w /etc/nebula/ -p wa -k mesh
-w /etc/nftables.conf -p wa -k firewall
-w /etc/phoenix/ -p wa -k phoenix
-w /var/log/lastlog -p wa -k logins'

SERVICES_OFF="cups cups-browsed bluetooth avahi-daemon ModemManager"
$KEEP_SERVICES && SERVICES_OFF=""   # Jerry 2026-10-06 (pbmIII): never stop a service that is set

nft_rules() {
  local ssh_rule=""
  if [[ -n "$SSH_FROM" ]]; then
    local v4="" v6=""
    for c in ${SSH_FROM//,/ }; do [[ "$c" == *:* ]] && v6+="$c, " || v4+="$c, "; done
    [[ -n "$v4" ]] && ssh_rule+="    ip saddr { ${v4%, } } tcp dport 22 accept comment \"break-glass ssh\"
"
    [[ -n "$v6" ]] && ssh_rule+="    ip6 saddr { ${v6%, } } tcp dport 22 accept comment \"break-glass ssh\"
"
  fi
  cat <<EOF
#!/usr/sbin/nft -f
# Phoenix baseline firewall ($VERSION) — generated by phoenix-harden.sh; edit the script, not this file
flush ruleset
table inet phoenix {
  chain input {
    type filter hook input priority filter; policy drop;
    iif lo accept
    ct state established,related accept
    ct state invalid drop
    iifname "nebula1" accept comment "mesh: Nebula's group firewall decides"
    ip protocol icmp icmp type { echo-request, destination-unreachable, time-exceeded, parameter-problem } accept
    ip6 nexthdr icmpv6 icmpv6 type { echo-request, destination-unreachable, packet-too-big, time-exceeded, parameter-problem, nd-router-advert, nd-neighbor-solicit, nd-neighbor-advert, mld-listener-query } accept
    udp dport 68 accept comment "dhcp v4 client"
    udp dport 546 accept comment "dhcp v6 client"
    udp dport 4242 accept comment "nebula"
${ssh_rule}    limit rate 5/minute log prefix "phoenix-drop: " level info
  }
  chain forward {
    type filter hook forward priority filter; policy drop;
  }
  chain output {
    type filter hook output priority filter; policy accept;
  }
}
EOF
}

write_baseline() {
  install -d -m 755 /etc/ssh/sshd_config.d /etc/sysctl.d /etc/audit/rules.d
  echo "$SSHD_CONF" > /etc/ssh/sshd_config.d/91-phoenix-harden.conf
  echo "$SYSCTL_CONF" > /etc/sysctl.d/90-phoenix-harden.conf
  echo "$AUDIT_RULES" > /etc/audit/rules.d/90-phoenix.rules
  nft_rules > $STATE/nftables.known-good
  # known-good copies for healing
  cp /etc/ssh/sshd_config.d/91-phoenix-harden.conf $STATE/sshd.known-good
  cp /etc/sysctl.d/90-phoenix-harden.conf $STATE/sysctl.known-good
  cp /etc/audit/rules.d/90-phoenix.rules $STATE/audit.known-good
  printf 'SSH_FROM_ARG="%s"\nKEEP_DESKTOP_ARG=%s\nKEEP_SERVICES_ARG=%s\n' "$SSH_FROM" "$KEEP_DESKTOP" "$KEEP_SERVICES" > $STATE/harden.conf
}

apply() {
  export DEBIAN_FRONTEND=noninteractive
  apt-get -y -q install nftables auditd unattended-upgrades >/dev/null
  write_baseline
  sshd -t -f /etc/ssh/sshd_config && systemctl reload ssh
  sysctl -q --system >/dev/null
  systemctl enable --now auditd >/dev/null 2>&1; augenrules --load >/dev/null 2>&1 || true
  for s in $SERVICES_OFF; do
    systemctl list-unit-files "$s.service" >/dev/null 2>&1 && { systemctl disable --now "$s" >/dev/null 2>&1 || true; systemctl mask "$s" >/dev/null 2>&1 || true; }
  done
  systemctl enable --now unattended-upgrades >/dev/null 2>&1 || true

  # firewall with automatic rollback
  nft list ruleset > $STATE/nftables.previous 2>/dev/null || true
  nft -c -f $STATE/nftables.known-good
  nft -f $STATE/nftables.known-good
  rm -f $STATE/firewall.confirmed
  systemd-run --quiet --on-active=120 --unit=phoenix-harden-rollback-$RANDOM \
    /bin/sh -c "[ -f $STATE/firewall.confirmed ] || { nft -f $STATE/nftables.previous 2>/dev/null || nft flush ruleset; logger -t phoenix-harden 'firewall NOT confirmed in 120 s: rolled back'; }"
  echo "$VERSION applied $(date -Is)" > $STATE/harden.VERSION
  install_heal
  log "baseline $VERSION applied — firewall rolls back in 120 s unless confirmed"
}

confirm() {
  touch $STATE/firewall.confirmed
  cp $STATE/nftables.known-good /etc/nftables.conf
  systemctl enable nftables >/dev/null 2>&1
  log "firewall confirmed and made permanent ($VERSION)"
}

install_heal() {
  install -m 755 "$(readlink -f "$0")" /usr/local/sbin/phoenix-harden
  cat > /etc/systemd/system/phoenix-harden-heal.service <<'EOF'
[Unit]
Description=Phoenix baseline self-heal

[Service]
Type=oneshot
ExecStart=/usr/local/sbin/phoenix-harden heal
EOF
  cat > /etc/systemd/system/phoenix-harden-heal.timer <<'EOF'
[Unit]
Description=Phoenix baseline self-heal every 15 min

[Timer]
OnBootSec=3min
OnUnitActiveSec=15min
Persistent=true

[Install]
WantedBy=timers.target
EOF
  systemctl daemon-reload
  systemctl enable --now phoenix-harden-heal.timer >/dev/null 2>&1
}

drift() {   # prints one line per drifted item; empty = clean
  cmp -s /etc/ssh/sshd_config.d/91-phoenix-harden.conf $STATE/sshd.known-good || echo "sshd"
  cmp -s /etc/sysctl.d/90-phoenix-harden.conf $STATE/sysctl.known-good || echo "sysctl-file"
  while IFS='=' read -r k v; do
    k=$(echo "$k" | xargs); v=$(echo "$v" | xargs); [[ -z "$k" ]] && continue
    [[ "$(sysctl -n "$k" 2>/dev/null)" == "$v" ]] || echo "sysctl:$k"
  done < $STATE/sysctl.known-good
  cmp -s /etc/audit/rules.d/90-phoenix.rules $STATE/audit.known-good || echo "audit-rules"
  systemctl is-active -q auditd || echo "auditd"
  [[ -f $STATE/firewall.confirmed ]] && { nft list table inet phoenix >/dev/null 2>&1 || echo "firewall"; }
  for s in $SERVICES_OFF; do systemctl is-active -q "$s" 2>/dev/null && echo "service:$s"; done
  local eff; eff=$(sshd -T 2>/dev/null || true)          # capture first: grep -q + pipefail = false alarm
  grep -qi '^passwordauthentication no' <<<"$eff" || echo "ssh-passwords"
  true
}

heal() {
  local d; d=$(drift)
  [[ -z "$d" ]] && return 0
  for item in $d; do
    case "$item" in
      sshd|ssh-passwords) cp $STATE/sshd.known-good /etc/ssh/sshd_config.d/91-phoenix-harden.conf; sshd -t && systemctl reload ssh ;;
      sysctl-file|sysctl:*) cp $STATE/sysctl.known-good /etc/sysctl.d/90-phoenix-harden.conf; sysctl -q --system >/dev/null ;;
      audit-rules) cp $STATE/audit.known-good /etc/audit/rules.d/90-phoenix.rules; augenrules --load >/dev/null 2>&1 || true ;;
      auditd) systemctl restart auditd ;;
      firewall) nft -f $STATE/nftables.known-good ;;
      service:*) s=${item#service:}; systemctl disable --now "$s" >/dev/null 2>&1; systemctl mask "$s" >/dev/null 2>&1 ;;
    esac
    log "drift healed: $item ($(cat $STATE/harden.VERSION 2>/dev/null))"
  done
}

case "$CMD" in
  apply)   apply ;;
  confirm) confirm ;;
  check)   d=$(drift); [[ -z "$d" ]] && echo "clean ($(cat $STATE/harden.VERSION 2>/dev/null))" || { echo "DRIFT:"; echo "$d" | sed 's/^/  /'; exit 1; } ;;
  heal)    heal ;;
  *) echo "usage: phoenix-harden.sh apply|confirm|check|heal [--ssh-from CIDRs]"; exit 2 ;;
esac
