// phase-html.js — Phoenix Office / Project Assist
// Renders a completed project phase into a plain, printable HTML page — the
// input LibreOffice converts to PDF via the exact same convertFile() call
// lib/document-html.js's output already uses (see main.js's exportPhasePdf).
//
// This is the "justify our role" artifact: the printed page carries the
// checklist's full decision trail (who decided what, against which source,
// why), not just checkmarks — that trail IS the evidence PBM's fee and its
// SBA/HUBZone self-performance positioning rest on.

const { letterheadHtml } = require('./document-html');

function esc(s) {
  return String(s == null ? '' : s).replace(/[&<>"]/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' }[c]));
}

const SOURCE_LABELS = {
  OSHA: 'OSHA / Federal',
  OK_STATE: 'Oklahoma State',
  CLIENT_SPEC: 'Client Spec',
  PM_BEST_PRACTICE: 'PM Best Practice',
};

function renderPhaseHtml({ project, phase, checklistItems, linkedDocs }) {
  const items = checklistItems || [];
  const docs = linkedDocs || [];

  const checklistRows = items.map(item => `<tr>
    <td class="src"><span class="badge">${esc(SOURCE_LABELS[item.source_type] || item.source_type)}</span>${item.source_ref ? `<div class="ref">${esc(item.source_ref)}</div>` : ''}</td>
    <td>${esc(item.label)}</td>
    <td class="disp disp-${esc(item.disposition)}">${esc(item.disposition)}</td>
    <td>${esc(item.rationale || '')}</td>
    <td class="who">${esc(item.decided_by || '')}${item.decided_at ? `<div class="when">${esc(item.decided_at)}</div>` : ''}</td>
  </tr>`).join('\n');

  const docRows = docs.map(d => `<li>${esc(d.title || d.hex)} — <span class="doc-state">${esc(d.state)}</span></li>`).join('\n');

  const costLine = (phase.estimated_cost != null || phase.actual_cost != null)
    ? `<p class="cost">Estimated: ${phase.estimated_cost != null ? '$' + esc(phase.estimated_cost) : '—'} &nbsp; Actual: ${phase.actual_cost != null ? '$' + esc(phase.actual_cost) : '—'}</p>`
    : '';
  const riskLine = phase.risk_level
    ? `<p class="risk risk-${esc(phase.risk_level)}">Risk: ${esc(phase.risk_level)}${phase.risk_notes ? ' — ' + esc(phase.risk_notes) : ''}</p>`
    : '';

  const letterhead = letterheadHtml();
  const h1Class = letterhead ? '' : ' class="no-letterhead"';

  return `<!doctype html>
<html><head><meta charset="utf-8"><title>Phase Report — ${esc(phase.label)}</title>
<style>
  body { font-family: 'Segoe UI', Arial, sans-serif; color: #1a1a1a; margin: 2.5cm; }
  .letterhead { display: flex; align-items: center; gap: 14pt; margin-bottom: 16pt;
    padding-bottom: 12pt; border-bottom: 2px solid #333; }
  .letterhead-logo svg { display: block; height: 40pt; width: auto; }
  .lh-name { font-size: 13pt; font-weight: 700; }
  .lh-addr { font-size: 9pt; color: #555; }
  h1 { font-size: 18pt; padding-bottom: 4pt; }
  h1.no-letterhead { border-bottom: 2px solid #333; }
  .subhead { font-size: 10pt; color: #555; margin-top: -4pt; margin-bottom: 12pt; }
  .cost, .risk { font-size: 10pt; margin: 4pt 0; }
  .risk-high { color: #a33; font-weight: 600; }
  .risk-medium { color: #a70; font-weight: 600; }
  .risk-low { color: #275; }
  table { width: 100%; border-collapse: collapse; margin-top: 14pt; font-size: 9.5pt; }
  th, td { text-align: left; padding: 6pt 8pt; border-bottom: 1px solid #ddd; vertical-align: top; }
  th { color: #555; font-weight: 600; }
  .badge { display: inline-block; padding: 1pt 6pt; border-radius: 3pt; background: #eee; font-size: 8pt; font-weight: 600; }
  .ref { font-size: 7.5pt; color: #777; margin-top: 2pt; }
  .disp-satisfied { color: #275; font-weight: 600; }
  .disp-not_applicable { color: #777; }
  .disp-open { color: #a33; font-weight: 600; }
  .who { font-size: 8.5pt; color: #555; }
  .when { font-size: 7.5pt; color: #999; }
  ul.docs { font-size: 9.5pt; margin-top: 6pt; }
  .doc-state { color: #777; font-size: 8.5pt; }
  .footer { margin-top: 24pt; font-size: 8pt; color: #999; }
</style></head>
<body>
  ${letterhead}
  <h1${h1Class}>${esc(project.name)} — ${esc(phase.label)}</h1>
  <p class="subhead">${esc(phase.lifecycle_stage)} phase — ${esc(phase.state)}${phase.completed_at ? ' — completed ' + esc(phase.completed_at) : ''}</p>
  ${costLine}
  ${riskLine}
  <table>
    <tr><th>Source</th><th>Item</th><th>Disposition</th><th>Rationale</th><th>Decided by</th></tr>
    ${checklistRows}
  </table>
  ${docs.length ? `<h3>Related documents</h3><ul class="docs">${docRows}</ul>` : ''}
  <p class="footer">Generated by Phoenix Office / Project Assist — this record reflects the project-management oversight performed for this phase, including the standard(s) each item was checked against and who made the determination.</p>
</body></html>`;
}

module.exports = { renderPhaseHtml };
