#!/usr/bin/env python3
"""suit_build.py — the package handler makes a suit correct before it is stored (Jerry 2026-10-09).

Phoenix DevOps OS | jwl247 | GPL v3

  python suit_build.py <source.py> <out.py> [--class entertainment|system]

Every suit leaves here able to answer the kernel the one way it listens for:
run(data, ...) returns JSON carrying "suit": <name>. Your code goes in unchanged; a shim at
the end does the rest:
  * your run() is called with only the arguments it accepts;
  * whatever it returns becomes a JSON object with "ok" and "suit" (a dict keeps its keys);
  * an exception becomes {"ok": false, "error": ...}, so a suit can never just stay silent;
  * a script with no run() is NOT run at import (that would execute inside the kernel at
    load); its body runs when the suit is run, and what it prints is the answer.
The header stamps the suit's class (entertainment unless asked otherwise). It sits inside the
bytes custody hashes, so the class cannot be changed after intake without failing the check.
Same input, same output: no timestamps, so an unchanged file never becomes a new version.
Exit codes: 0 built · 2 not a Python suit (syntax error, unreadable) · 1 usage.
"""

import ast
import hashlib
import sys
from pathlib import Path

HEADER = "# phoenix-suit:"
SHIM_MARK = "# ---- phoenix-suit shim (generated by the package handler; edit your original, not this) ----"
CLASSES = ("entertainment", "system")

SHIM = '''
{mark}
import json as _phx_json, inspect as _phx_inspect, io as _phx_io, contextlib as _phx_ctx
_PHX_SUIT = {name!r}
{body_setup}

def _phx_answer(r):
    if isinstance(r, (bytes, bytearray)):
        r = r.decode("utf-8", "replace")
    if isinstance(r, str):
        try:
            parsed = _phx_json.loads(r)
            r = parsed if isinstance(parsed, dict) else {{"result": parsed}}
        except ValueError:
            r = {{"result": r}}
    elif not isinstance(r, dict):
        r = {{"result": r}}
    r = dict(r)
    r.setdefault("ok", True)
    r["suit"] = _PHX_SUIT
    return _phx_json.dumps(r, default=str)


def run(data, ball=None, pcs=None, **kw):
    try:
{call}
    except BaseException as e:  # a suit never goes silent, whatever happens inside it
        return _phx_json.dumps({{"ok": False, "suit": _PHX_SUIT, "error": f"{{type(e).__name__}}: {{e}}"}})
'''

CALL_WITH_RUN = '''        params = _phx_inspect.signature(_phx_user_run).parameters
        takes_any = any(p.kind is p.VAR_KEYWORD for p in params.values())
        extra = {k: v for k, v in dict(ball=ball, pcs=pcs, **kw).items() if takes_any or k in params}
        return _phx_answer(_phx_user_run(data, **extra) if params else _phx_user_run())'''

CALL_SCRIPT = '''        out = _phx_io.StringIO()
        with _phx_ctx.redirect_stdout(out):
            exec(compile(_PHX_SOURCE, "<suit " + _PHX_SUIT + ">", "exec"), {"__name__": "__main__", "data": data})
        return _phx_answer({"output": out.getvalue()})'''


def strip_build(text: str) -> str:
    """The original code of an already-built suit (rebuilding never wraps a wrapper)."""
    if not text.startswith(HEADER):
        return text
    lines = text.splitlines(keepends=True)
    body = "".join(l for l in lines if not l.startswith(HEADER) and not l.startswith("# built by the package handler"))
    if SHIM_MARK in body:
        body = body.split("\n" + SHIM_MARK, 1)[0]
    if body.startswith("_PHX_SOURCE = "):        # a wrapped plain script: the source is a literal
        body = ast.literal_eval(body[len("_PHX_SOURCE = "):].strip())
    return body.rstrip("\n") + "\n"


def build(src_text: str, name: str, cls: str) -> str:
    original = strip_build(src_text)
    tree = ast.parse(original)                       # SyntaxError -> not a suit
    has_run = any(isinstance(n, (ast.FunctionDef, ast.AsyncFunctionDef)) and n.name == "run" for n in tree.body)
    sha3 = hashlib.sha3_512(original.encode("utf-8")).hexdigest()
    head = (f"{HEADER} name={name} class={cls} src-sha3={sha3[:32]}\n"
            "# built by the package handler (sector2/package-handler/suit_build.py): your code, unchanged, then the shim.\n")
    if has_run:
        body = original
        setup = '_phx_user_run = globals()["run"]'
        call = CALL_WITH_RUN
    else:
        body = "_PHX_SOURCE = " + repr(original) + "\n"
        setup = ""
        call = CALL_SCRIPT
    return head + body.rstrip("\n") + "\n" + SHIM.format(mark=SHIM_MARK, name=name, body_setup=setup, call=call)


def main(argv):
    args = [a for a in argv if not a.startswith("--class")]
    cls = "entertainment"
    for i, a in enumerate(argv):
        if a == "--class" and i + 1 < len(argv):
            cls = argv[i + 1]
        elif a.startswith("--class="):
            cls = a.split("=", 1)[1]
    args = [a for a in args if a not in CLASSES]
    if len(args) != 2 or cls not in CLASSES:
        print(__doc__.split("\n\n")[1], file=sys.stderr)
        return 1
    src, out = Path(args[0]), Path(args[1])
    try:
        text = src.read_text(encoding="utf-8")
        built = build(text, src.stem, cls)
    except (OSError, UnicodeDecodeError) as e:
        print(f"suit_build: can't read {src}: {e}", file=sys.stderr)
        return 2
    except SyntaxError as e:
        print(f"suit_build: {src.name} is not a working Python suit: line {e.lineno}: {e.msg}", file=sys.stderr)
        return 2
    compile(built, str(out), "exec")                 # the built suit must itself compile
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(built, encoding="utf-8", newline="\n")
    print(f"suit_build: {src.name} -> {cls} suit ({'run() wrapped' if 'globals()[\"run\"]' in built else 'script wrapped'})")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
