#!/usr/bin/env bash
# dataplane-up.sh — stand up (or re-check) a Phoenix data plane on a Cloudflare
# account: an R2 bucket, a D1 database with the Phoenix custody schema, and
# packages-worker deployed against them under its own name and its own
# PHOENIX_AUTH. Step 1 of "Phoenix from the cloud, a worker on the ground"
# (docs/plans/compaq-road-test-plan.md, Phase 0 + Phase 5).
#
#   dataplane-up.sh <name>        e.g.  dataplane-up.sh phoenix-roadtest
#   dataplane-up.sh <name> check  verify only, change nothing
#
# Re-runnable: every step looks before it creates, and the worker is only
# redeployed when index.js changed since the last deploy.
#
# Env (read, never printed):
#   CF_API_TOKEN    Cloudflare API token for the TARGET account
#                   (Workers Scripts Edit, D1 Edit, Workers R2 Storage Edit)
#   CF_ACCOUNT_ID   the target account's id
# State (outside the repo, 0600): ~/.phoenix/worker-up/<name>/
#   wrangler.jsonc  generated config (ids, not secrets)
#   auth            this data plane's PHOENIX_AUTH — shared with nothing else
#   deployed.sha    sha256 of the index.js last deployed
#   url             the worker's workers.dev URL
set -euo pipefail

NAME=${1:?usage: dataplane-up.sh <name> [check]}
MODE=${2:-up}
[[ "$NAME" =~ ^[a-z0-9-]{3,40}$ ]] || { echo "name must be 3-40 of a-z 0-9 -"; exit 2; }
: "${CF_API_TOKEN:?CF_API_TOKEN not set}"
: "${CF_ACCOUNT_ID:?CF_ACCOUNT_ID not set}"

REPO=$(cd "$(dirname "$0")/../.." && pwd)
WORKER_DIR="$REPO/sector2/package-handler/worker"
SCHEMA="$WORKER_DIR/schema-d1.sql"
STATE="$HOME/.phoenix/worker-up/$NAME"
API="https://api.cloudflare.com/client/v4/accounts/$CF_ACCOUNT_ID"
mkdir -p "$STATE"; chmod 700 "$STATE" 2>/dev/null || true

say()  { printf '  %-10s %s\n' "$1" "$2"; }
die()  { say "FAIL" "$*"; exit 1; }
api()  { # method path [json-body] -> response body on stdout
  local m=$1 p=$2
  if [[ $# -ge 3 ]]; then
    curl -s -X "$m" -H "Authorization: Bearer $CF_API_TOKEN" -H "Content-Type: application/json" "$API$p" --data "$3"
  else
    curl -s -X "$m" -H "Authorization: Bearer $CF_API_TOKEN" "$API$p"
  fi
}
jq_py() { python -c "import json,sys; d=json.load(sys.stdin); $1"; }
wr() { # wrangler against the TARGET account only
  (cd "$WORKER_DIR" && CLOUDFLARE_API_TOKEN="$CF_API_TOKEN" CLOUDFLARE_ACCOUNT_ID="$CF_ACCOUNT_ID" \
     npx --yes wrangler "$@" -c "$STATE/wrangler.jsonc")
}
sha256() { python -c "import hashlib,sys; print(hashlib.sha256(open(sys.argv[1],'rb').read()).hexdigest())" "$1"; }

echo "== dataplane $NAME ($MODE) on account ${CF_ACCOUNT_ID:0:6}…"

# ── 1. R2 bucket ─────────────────────────────────────────────────────────
have_bucket=$(api GET "/r2/buckets/$NAME" | jq_py "print('yes' if d.get('success') else 'no')")
if [[ $have_bucket == yes ]]; then say "r2" "bucket $NAME exists"
elif [[ $MODE == check ]]; then die "r2 bucket $NAME missing"
else
  api POST /r2/buckets "{\"name\":\"$NAME\"}" | jq_py "sys.exit(0 if d.get('success') else print(d.get('errors')) or 1)" \
    || die "could not create bucket"
  say "r2" "bucket $NAME created"
fi

# ── 2. D1 database ───────────────────────────────────────────────────────
DB_ID=$(api GET "/d1/database?name=$NAME" | jq_py "r=[x for x in d.get('result') or [] if x['name']=='$NAME']; print(r[0]['uuid'] if r else '')")
if [[ -n $DB_ID ]]; then say "d1" "database $NAME exists (${DB_ID:0:8}…)"
elif [[ $MODE == check ]]; then die "d1 database $NAME missing"
else
  DB_ID=$(api POST /d1/database "{\"name\":\"$NAME\"}" | jq_py "print((d.get('result') or {}).get('uuid',''))")
  [[ -n $DB_ID ]] || die "could not create D1 $NAME"
  say "d1" "database $NAME created (${DB_ID:0:8}…)"
fi

# ── 3. wrangler config (generated, ids only) ─────────────────────────────
cat > "$STATE/wrangler.jsonc" <<EOF
// Generated by sector3/worker-up/dataplane-up.sh — do not edit by hand.
{
  "name": "$NAME",
  "main": "$(cd "$WORKER_DIR" && pwd -W 2>/dev/null || pwd)/index.js",
  "compatibility_date": "2025-01-01",
  "workers_dev": true,
  "d1_databases": [ { "binding": "PHOENIX_DB", "database_name": "$NAME", "database_id": "$DB_ID" } ],
  "r2_buckets":   [ { "binding": "CLONEPOOL_BUCKET", "bucket_name": "$NAME" } ]
}
EOF

# ── 4. schema ────────────────────────────────────────────────────────────
want=$(grep -c "^CREATE TABLE" "$SCHEMA")
count_tables() {
  api POST "/d1/database/$DB_ID/query" '{"sql":"SELECT count(*) AS n FROM sqlite_master WHERE type='"'"'table'"'"' AND name NOT LIKE '"'"'sqlite_%'"'"' AND name NOT LIKE '"'"'_cf_%'"'"'"}' \
    | jq_py "print(d['result'][0]['results'][0]['n'] if d.get('success') else -1)"
}
have=$(count_tables)
if [[ $have -ge $want ]]; then say "schema" "$have/$want tables present"
elif [[ $MODE == check ]]; then die "schema: $have/$want tables"
elif [[ $have -eq 0 ]]; then
  wr d1 execute "$NAME" --remote --file "$SCHEMA" --yes >/dev/null || die "schema load failed"
  have=$(count_tables); [[ $have -ge $want ]] || die "schema: only $have/$want tables after load"
  say "schema" "loaded, $have/$want tables"
else
  die "schema: database has $have/$want tables — partial; not touching a non-empty database, fix by hand"
fi

# ── 5. this data plane's own PHOENIX_AUTH ────────────────────────────────
new_auth=no
if [[ ! -s "$STATE/auth" ]]; then
  [[ $MODE == check ]] && die "no auth secret in $STATE"
  python -c "import secrets; print(secrets.token_hex(32))" > "$STATE/auth"
  chmod 600 "$STATE/auth" 2>/dev/null || true
  new_auth=yes
fi

# ── 6. deploy (only when index.js changed) ───────────────────────────────
cur=$(sha256 "$WORKER_DIR/index.js")
last=$(cat "$STATE/deployed.sha" 2>/dev/null || true)
if [[ $cur == "$last" && $new_auth == no ]]; then say "worker" "index.js unchanged since last deploy (${cur:0:12})"
elif [[ $MODE == check ]]; then die "worker not at current index.js (deployed ${last:0:12}, repo ${cur:0:12})"
else
  wr deploy >"$STATE/deploy.log" 2>&1 || { tail -20 "$STATE/deploy.log"; die "deploy failed (log: $STATE/deploy.log)"; }
  if [[ $new_auth == yes ]]; then
    wr secret put PHOENIX_AUTH < "$STATE/auth" >/dev/null 2>&1 || die "could not set PHOENIX_AUTH"
  fi
  echo "$cur" > "$STATE/deployed.sha"
  say "worker" "deployed $NAME at index.js ${cur:0:12}"
fi

# ── 7. prove it ──────────────────────────────────────────────────────────
SUB=$(api GET /workers/subdomain | jq_py "print((d.get('result') or {}).get('subdomain',''))")
URL="https://$NAME.$SUB.workers.dev"; echo "$URL" > "$STATE/url"
h=""; for i in 1 2 3 4 5 6; do h=$(curl -s -o /dev/null -w '%{http_code}' "$URL/health"); [[ $h == 200 ]] && break; sleep 5; done
[[ $h == 200 ]] || die "$URL/health -> $h"
a=$(curl -s -o /dev/null -w '%{http_code}' -H "Authorization: Bearer $(cat "$STATE/auth")" "$URL/stats")
n=$(curl -s -o /dev/null -w '%{http_code}' "$URL/stats")
[[ $a == 200 ]] || die "$URL/stats with auth -> $a"
[[ $n == 401 ]] || die "$URL/stats WITHOUT auth -> $n (must be 401)"
say "proof" "$URL  /health 200 · /stats authed 200 · unauthed 401"
echo "== dataplane $NAME ready"
